// AUTO-GENERATED by scripts/gen-galleries.mjs — do not edit by hand.
// Project slug -> ordered gallery images (display order 01, 02, ...).
export interface GalleryImage {
  src: string;
  width: number;
  height: number;
}

export const GALLERIES: Record<string, GalleryImage[]> = {
  "board-and-batten-warkworth": [
    {
      "src": "/projects/board-and-batten-warkworth/01.jpg",
      "width": 2500,
      "height": 1875
    },
    {
      "src": "/projects/board-and-batten-warkworth/02.jpg",
      "width": 2500,
      "height": 1875
    },
    {
      "src": "/projects/board-and-batten-warkworth/03.jpg",
      "width": 2500,
      "height": 1875
    },
    {
      "src": "/projects/board-and-batten-warkworth/04.jpg",
      "width": 2500,
      "height": 1875
    }
  ],
  "langs-beach-new-build": [
    {
      "src": "/projects/langs-beach-new-build/01.jpg",
      "width": 1500,
      "height": 1028
    },
    {
      "src": "/projects/langs-beach-new-build/02.jpg",
      "width": 1500,
      "height": 1028
    },
    {
      "src": "/projects/langs-beach-new-build/03.jpg",
      "width": 1500,
      "height": 1028
    },
    {
      "src": "/projects/langs-beach-new-build/04.jpg",
      "width": 1500,
      "height": 1028
    },
    {
      "src": "/projects/langs-beach-new-build/05.jpg",
      "width": 1500,
      "height": 1028
    },
    {
      "src": "/projects/langs-beach-new-build/06.jpg",
      "width": 1500,
      "height": 1028
    },
    {
      "src": "/projects/langs-beach-new-build/07.jpg",
      "width": 1500,
      "height": 1028
    },
    {
      "src": "/projects/langs-beach-new-build/08.jpg",
      "width": 1500,
      "height": 1028
    },
    {
      "src": "/projects/langs-beach-new-build/09.jpg",
      "width": 1500,
      "height": 1028
    },
    {
      "src": "/projects/langs-beach-new-build/10.jpg",
      "width": 1500,
      "height": 1028
    },
    {
      "src": "/projects/langs-beach-new-build/11.jpg",
      "width": 1500,
      "height": 1028
    },
    {
      "src": "/projects/langs-beach-new-build/12.jpg",
      "width": 1500,
      "height": 1028
    }
  ],
  "langs-waterfront-new-build": [
    {
      "src": "/projects/langs-waterfront-new-build/01.webp",
      "width": 2500,
      "height": 1667
    },
    {
      "src": "/projects/langs-waterfront-new-build/02.webp",
      "width": 2500,
      "height": 1667
    },
    {
      "src": "/projects/langs-waterfront-new-build/03.webp",
      "width": 1500,
      "height": 1000
    },
    {
      "src": "/projects/langs-waterfront-new-build/04.webp",
      "width": 1500,
      "height": 2000
    },
    {
      "src": "/projects/langs-waterfront-new-build/05.webp",
      "width": 1500,
      "height": 1000
    },
    {
      "src": "/projects/langs-waterfront-new-build/06.webp",
      "width": 1500,
      "height": 2250
    }
  ],
  "little-manly-cliff-house": [
    {
      "src": "/projects/little-manly-cliff-house/01.jpg",
      "width": 2500,
      "height": 1875
    },
    {
      "src": "/projects/little-manly-cliff-house/02.jpg",
      "width": 1500,
      "height": 1125
    },
    {
      "src": "/projects/little-manly-cliff-house/03.jpg",
      "width": 2500,
      "height": 1875
    },
    {
      "src": "/projects/little-manly-cliff-house/04.jpg",
      "width": 2500,
      "height": 1875
    },
    {
      "src": "/projects/little-manly-cliff-house/05.jpg",
      "width": 2500,
      "height": 1875
    },
    {
      "src": "/projects/little-manly-cliff-house/06.jpg",
      "width": 2500,
      "height": 1875
    },
    {
      "src": "/projects/little-manly-cliff-house/07.jpg",
      "width": 2500,
      "height": 1875
    },
    {
      "src": "/projects/little-manly-cliff-house/08.jpg",
      "width": 2500,
      "height": 1875
    }
  ],
  "mangawhai-estuary-new-build": [
    {
      "src": "/projects/mangawhai-estuary-new-build/01.jpg",
      "width": 1080,
      "height": 720
    },
    {
      "src": "/projects/mangawhai-estuary-new-build/02.jpg",
      "width": 932,
      "height": 808
    },
    {
      "src": "/projects/mangawhai-estuary-new-build/03.jpg",
      "width": 1080,
      "height": 596
    },
    {
      "src": "/projects/mangawhai-estuary-new-build/04.jpg",
      "width": 1080,
      "height": 720
    }
  ],
  "mount-eden-factory": [
    {
      "src": "/projects/mount-eden-factory/01.jpg",
      "width": 2500,
      "height": 1875
    }
  ],
  "sudima-hotel-mural": [
    {
      "src": "/projects/sudima-hotel-mural/01.jpg",
      "width": 1500,
      "height": 2010
    },
    {
      "src": "/projects/sudima-hotel-mural/02.jpg",
      "width": 1500,
      "height": 2010
    }
  ],
  "waipu-bach": [
    {
      "src": "/projects/waipu-bach/01.jpg",
      "width": 1080,
      "height": 720
    },
    {
      "src": "/projects/waipu-bach/02.jpg",
      "width": 1080,
      "height": 1619
    },
    {
      "src": "/projects/waipu-bach/03.webp",
      "width": 1500,
      "height": 1000
    },
    {
      "src": "/projects/waipu-bach/04.webp",
      "width": 2500,
      "height": 1667
    }
  ]
};

/** First image of a project's gallery, or undefined if none. */
export function leadImage(slug: string): GalleryImage | undefined {
  return GALLERIES[slug]?.[0];
}
